export const ProjectsData = [
    {
        key: 1,
        title: "Portfolio | S.R Dragonfang",
        subtitle: "Portfolio Website",
        background: "dark",
        languages: "ReactJS, SCSS",
        responsive: "375px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/portfolio.png",
        mobilePath: "../assets/images/products/portfolio.png",
        previewURL: "https://srdf-portfolio.web.app/",
        sourceURL: "https://github.com/srdragonfang/React-Porfolio"
    },
    {
        key: 2,
        title: "Sokunmaru | Desk",
        subtitle: "MusicPlayer App, Clock App, Todo App, Note App, Kanban App",
        background: "dark",
        languages: "ReactJS, SCSS, API",
        responsive: "1024px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/sokunmaru-desk.png",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-desk.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-desk"
    },
    {
        key: 3,
        title: "Clone | Gmail",
        subtitle: "Form Validate",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/gmail-laptop.jpg",
        mobilePath: "../assets/images/products/gmail-mobile.jpg",
        previewURL: "sokunmaru-gmail-clone.web.app",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-gmail-clone"
    },
    {
        key: 4,
        title: "Sokunmaru | A Million Dreams",
        subtitle: "NETFLIX Clone | Social film discovery",
        background: "dark",
        languages: "ReactJS, CSS, Axios, Atlasian Icons, react-icons, youtube-media",
        responsive: "375px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/amilliondreams-laptop.png",
        mobilePath: "../assets/images/products/amilliondreams-mobile.png",
        previewURL: "https://sokunmaru-amilliondreams.web.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-AMillionDreams"
    },
    {
        key: 5,
        title: "Sokunmaru | Cinema",
        subtitle: "Movie Booking Seats",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "1024px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/cinema-laptop.jpg",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-cinema.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-cinema"
    },
    {
        key: 6,
        title: "Form | Validate",
        subtitle: "Form Validate",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/form-validate-laptop.png",
        mobilePath: "../assets/images/products/form-validate-laptop.png",
        previewURL: "https://sokunmaru-validate.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/form-validate"
    },
    {
        key: 7,
        title: "Sokunmaru | Newspaper",
        subtitle: "Newspaper",
        background: "dark",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/newspaper.jpg",
        mobilePath: "../assets/images/products/newspaper.jpg",
        previewURL: "https://sokunmaru-newspaper.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-newspaper"
    },
    {
        key: 8,
        title: "Sokunmaru | CoffeeShop",
        subtitle: "Landing Page",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/coffee-shop-laptop.png",
        mobilePath: "../assets/images/products/coffee-shop-mobile.png",
        previewURL: "https://sokunmaru-coffeshop.netlify.app",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-coffeeShop"
    },
    {
        key: 9,
        title: "Sokunmaru | Counter App",
        subtitle: "Class Function",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/form-validate-laptop.png",
        mobilePath: "../assets/images/products/form-validate-laptop.png",
        previewURL: "https://sokunmaru-validate.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/form-validate"
    }
]