export const ProjectsData = [
    {
        key: 1,
        title: "Portfolio | S.R Dragonfang",
        subtitle: "Portfolio Website",
        background: "dark",
        languages: "ReactJS, SCSS",
        responsive: "375px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/portfolio.png",
        mobilePath: "../assets/images/products/portfolio.png",
        previewURL: "https://srdragonfang-portfolio.web.app/portfolio",
        sourceURL: "https://github.com/srdragonfang/srdragonfang-portfolio"
    },
    {
        key: 2,
        title: "Sokunmaru | A Million Dreams",
        subtitle: "NETFLIX Clone | Social film discovery",
        background: "dark",
        languages: "ReactJS, CSS, Axios, Atlasian Icons, react-icons, youtube-media",
        responsive: "375px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/amilliondreams-laptop.png",
        mobilePath: "../assets/images/products/amilliondreams-mobile.png",
        previewURL: "https://sokunmaru-amilliondreams.web.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-AMillionDreams"
    },
    {
        key: 3,
        title: "Sokunmaru's Desk | Kanban",
        subtitle: "Kanban App",
        background: "dark",
        languages: "HTML, SCSS",
        responsive: "1024px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/kanbanApp.png",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-kanban.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-kanban"
    },
    {
        key: 4,
        title: "Sokunmaru's Desk | Write!",
        subtitle: "Note App",
        background: "dark",
        languages: "HTML, SCSS",
        responsive: "1024px",
        deploy: "Firebase",
        laptopPath: "../assets/images/products/writeApp.png",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-writeapp.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-writeApp"
    },
    {
        key: 5,
        title: "Sokunmaru's Desk | ToDo!",
        subtitle: "To Do App",
        background: "dark",
        languages: "HTML, SCSS",
        responsive: "1024px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/todoApp.png",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-todoapp.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-todoApp"
    },
    {
        key: 6,
        title: "Sokunmaru | Cinema",
        subtitle: "Movie Booking Seats",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "1024px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/cinema-laptop.png",
        mobilePath: "../assets/images/products/no-responsive.jpg",
        previewURL: "https://sokunmaru-cinema.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-cinema"
    },    {
        key: 7,
        title: "Form Validate",
        subtitle: "Form Validate",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/form-validate-laptop.png",
        mobilePath: "../assets/images/products/form-validate-laptop.png",
        previewURL: "https://sokunmaru-validate.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/form-validate"
    },
    {
        key: 7,
        title: "Sokunmaru | Newspaper",
        subtitle: "Newspaper",
        background: "dark",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/newspaper.jpg",
        mobilePath: "../assets/images/products/newspaper.jpg",
        previewURL: "https://sokunmaru-newspaper.netlify.app/",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-newspaper"
    },
    {
        key: 8,
        title: "Sokunmaru | CoffeeShop",
        subtitle: "Landing Page",
        background: "",
        languages: "HTML5, CSS3, Javascript",
        responsive: "375px",
        deploy: "Netlify",
        laptopPath: "../assets/images/products/coffee-shop-laptop.png",
        mobilePath: "../assets/images/products/coffee-shop-mobile.png",
        previewURL: "https://sokunmaru-coffeshop.netlify.app",
        sourceURL: "https://github.com/srdragonfang/sokunmaru-coffeeShop"
    }

]