export const ProjectsData = [
	{
		key: 0,
		title: 'AUTHOR',
		subtitle: '',
		background: 'dark',
		languages: 'Mongoose, ExpressJS, NodeJS, ReactJS, Chakra-UI, Redux, Redux-Saga, nodemon, cors, body-parser, framer-motion',
		design: '',
		responsive: '375px',
		deploy: 'client: Netify; server: Heroku',
		laptopPath: '../assets/images/products/authorApp.png',
		mobilePath: '../assets/images/products/authorApp.png',
		previewURL: 'https://sokunmaru-author.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-author-app',
	},
	{
		key: 1,
		title: 'Portfolio | S.R Dragonfang',
		subtitle: 'Portfolio Website',
		background: 'dark',
		languages: 'ReactJS, SCSS',
		design: '',
		responsive: '375px',
		deploy: 'Firebase',
		laptopPath: '../assets/images/products/portfolio.png',
		mobilePath: '../assets/images/products/portfolio.png',
		previewURL: 'https://srdragonfang-portfolio.web.app/portfolio',
		sourceURL: 'https://github.com/srdragonfang/srdragonfang-portfolio',
	},
	{
		key: 2,
		title: 'A Million Dreams',
		subtitle: 'NETFLIX Clone | Social film discovery',
		background: 'dark',
		languages:
			'ReactJS, CSS, Axios, Atlasian Icons, react-icons, youtube-media',
		design: '',
		responsive: '375px',
		deploy: 'Firebase',
		laptopPath: '../assets/images/products/amilliondreams-laptop.png',
		mobilePath: '../assets/images/products/amilliondreams-mobile.png',
		previewURL: 'https://sokunmaru-amilliondreams.web.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-AMillionDreams',
	},
	{
		key: 3,
		title: "Kanban App",
		subtitle: 'Kanban App',
		background: 'dark',
		languages: 'HTML, SCSS',
		design: '',
		responsive: '1024px',
		deploy: 'Firebase',
		laptopPath: '../assets/images/products/kanbanApp.png',
		mobilePath: '../assets/images/products/no-responsive.jpg',
		previewURL: 'https://sokunmaru-kanban.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-kanban',
	},
	{
		key: 4,
		title: "Sokunmaru's Desk | Write!",
		subtitle: 'Note App',
		background: 'dark',
		languages: 'HTML, SCSS',
		design: '',
		responsive: '1024px',
		deploy: 'Firebase',
		laptopPath: '../assets/images/products/writeApp.png',
		mobilePath: '../assets/images/products/no-responsive.jpg',
		previewURL: 'https://sokunmaru-writeapp.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-writeApp',
	},
	{
		key: 5,
		title: "Sokunmaru's Desk | ToDo!",
		subtitle: 'To-do App',
		background: 'dark',
		languages: 'HTML, SCSS',
		design: '',
		responsive: '1024px',
		deploy: 'Netlify',
		laptopPath: '../assets/images/products/todoApp.png',
		mobilePath: '../assets/images/products/no-responsive.jpg',
		previewURL: 'https://sokunmaru-todoapp.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-todoApp',
	},
	{
		key: 6,
		title: 'Netflix | Clone',
		subtitle: 'Netflix Website',
		background: '',
		languages: 'React, CSS, Axios',
		design: '',
		responsive: '375px',
		deploy: 'Firebase',
		laptopPath: '../assets/images/products/netflixClone.png',
		mobilePath: '../assets/images/products/coffee-shop-mobile.png',
		previewURL: 'https://netflix-clone-srdf.web.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-Netflix-Clone',
	},
	{
		key: 7,
		title: 'Contact Form',
		subtitle: 'Form',
		background: '',
		languages: 'HTML, CSS, Bootstrap',
		design: '',
		responsive: '375px',
		deploy: 'Netlify',
		laptopPath: '../assets/images/products/form-validate-laptop.png',
		mobilePath: '../assets/images/products/form-validate-laptop.png',
		previewURL: 'https://sokunmaru-validate.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/form-validate',
	},
	{
		key: 8,
		title: 'Sokunmaru | Cinema',
		subtitle: 'Movie Booking Seats',
		background: '',
		languages: 'HTML5, CSS3, Javascript',
		design: '',
		responsive: '1024px',
		deploy: 'Netlify',
		laptopPath: '../assets/images/products/cinema-laptop.png',
		mobilePath: '../assets/images/products/no-responsive.jpg',
		previewURL: 'https://sokunmaru-cinema.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-cinema',
	},

	{
		key: 9,
		title: 'TheBox Company',
		subtitle: 'The Landing Page',
		background: 'dark',
		languages: 'HTML, CSS',
		design: 'https://www.figma.com/file/6G0cjvHzGwnS3GgqBnR24v/Responsive%2FComponents-Landing-Page---Construction-Company-(Community)?node-id=47%3A347',
		responsive: '1366px',
		deploy: 'Netlify',
		laptopPath: '../assets/images/products/theBox.png',
		mobilePath: '../assets/images/products/newspaper.jpg',
		previewURL: 'https://sokunmaru-thebox.netlify.app/',
		sourceURL: 'https://github.com/srdragonfang/sokunmaru-thebox',
	}
	// {
	// 	key: 10,
	// 	title: 'Sokunmaru | Newspaper',
	// 	subtitle: 'The Landing Page',
	// 	background: 'dark',
	// 	languages: 'HTML5, CSS3, Javascript',
	// 	design: '',
	// 	responsive: '375px',
	// 	deploy: 'Netlify',
	// 	laptopPath: '../assets/images/products/newspaper.jpg',
	// 	mobilePath: '../assets/images/products/newspaper.jpg',
	// 	previewURL: 'https://sokunmaru-newspaper.netlify.app/',
	// 	sourceURL: 'https://github.com/srdragonfang/sokunmaru-newspaper',
	// },
	// {
	// 	key: 11,
	// 	title: 'Sokunmaru | CoffeeShop',
	// 	subtitle: 'The Landing Page',
	// 	background: '',
	// 	languages: 'HTML5, CSS3, Javascript',
	// 	design: '',
	// 	responsive: '375px',
	// 	deploy: 'Netlify',
	// 	laptopPath: '../assets/images/products/coffee-shop-laptop.png',
	// 	mobilePath: '../assets/images/products/coffee-shop-mobile.png',
	// 	previewURL: 'https://sokunmaru-coffeshop.netlify.app',
	// 	sourceURL: 'https://github.com/srdragonfang/sokunmaru-coffeeShop',
	// },
	// {
	// 	key: 12,
	// 	title: 'Couter App',
	// 	subtitle: 'Couter App With Class Function',
	// 	background: '',
	// 	languages: 'HTML, SCSS, Javascript',
	// 	design: '',
	// 	responsive: '375px',
	// 	deploy: 'Netlify',
	// 	laptopPath: '../assets/images/products/couterApp.png',
	// 	mobilePath: '../assets/images/products/coffee-shop-mobile.png',
	// 	previewURL: 'https://sokunmaru-coffeshop.netlify.app',
	// 	sourceURL:
	// 		'https://github.com/srdragonfang/couter-app-with-class-function',
	// },
];
